name: data-science
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - requests
  - beautifulsoup4
  - numpy=1.19.1
  - pandas=1.1.1
  - matplotlib=3.2.2
  - xlrd
  - openpyxl
  - scikit-learn=0.23.2
